chat/urls.py
# chat/urls.py

from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.home,name = 'home'),
    path('<str:room_name>', views.home,name = 'home'),
    path('create_friend/<int:id>', views.create_friend, name ='create_friend'),
]

djangochannel/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat')),
    path('user/', include('user.urls', namespace='user')),
]

user/urls.py
from django.urls import path, include

from .views import login_page, logout_page,register

app_name = 'user'

urlpatterns = [
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register, name='register'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
import uuid

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name = 'profile_detail')
    '''
       Add other fields...
    '''
    is_online = models.BooleanField(default = False)

class ChatSession(models.Model):
    user1 = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user1_name')
    user2 = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user2_name')
    updated_on = models.DateTimeField(auto_now = True)
    
    class Meta:
        unique_together = (("user1", "user2"))
        verbose_name = 'Chat Message'
        
    def __str__(self):
        return '%s_%s' %(self.user1.username,self.user2.username)
        
    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    @staticmethod
    def chat_session_exists(user1,user2):
        return ChatSession.objects.filter(Q(user1=user1, user2=user2) | Q(user1=user2, user2=user1)).first()
    
    @staticmethod
    def create_if_not_exists(user1,user2):
        res = ChatSession.chat_session_exists(user1,user2)
        return False if res else ChatSession.objects.create(user1=user1,user2=user2)
    
class ChatMessage(models.Model):
    id = models.UUIDField(primary_key = True,editable = False)
    chat_session = models.ForeignKey(ChatSession,on_delete=models.CASCADE,related_name='user_messages')
    user = models.ForeignKey(User, verbose_name='message_sender',on_delete=models.CASCADE)
    message_detail = models.JSONField()

    class Meta:
        ordering = ['-message_detail__timestamp']
    
    def __str__(self):
        return '%s' %(self.message_detail["timestamp"])

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        ChatSession.objects.get(id = self.chat_session.id).save()   # Update ChatSession TimeStampe

    @staticmethod
    def count_overall_unread_msg(user_id):
        total_unread_msg = 0
        user_all_friends = ChatSession.objects.filter(Q(user1__id = user_id) | Q(user2__id = user_id))
        for ch_session in user_all_friends:
            un_read_msg_count = ChatMessage.objects.filter(chat_session = ch_session.id,message_detail__read = False).exclude(user__id = user_id).count()        
            total_unread_msg += un_read_msg_count
        return total_unread_msg

    @staticmethod
    def meassage_read_true(message_id):
        msg_inst = ChatMessage.objects.filter(id = message_id).first()
        msg_inst.message_detail['read'] = True
        msg_inst.save(update_fields = ['message_detail',])
        return None

    @staticmethod
    def all_msg_read(room_id,user):
        all_msg = ChatMessage.objects.filter(chat_session = room_id,message_detail__read = False).exclude(user__username = user)
        for msg in all_msg:
            msg.message_detail['read'] = True
            msg.save(update_fields = ['message_detail',])
        return None

    @staticmethod
    def sender_inactive_msg(message_id):
        return ChatMessage.objects.filter(id = message_id).update(message_detail__Sclr = True)

    @staticmethod
    def receiver_inactive_msg(message_id):
        return ChatMessage.objects.filter(id = message_id).update(message_detail__Rclr = True)

chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import *
from django.http.response import HttpResponse, HttpResponseRedirect
from django.contrib import messages

@login_required
def home(request, room_name=None):
    # count all unread message
    unread_msg = ChatMessage.count_overall_unread_msg(request.user.id)

    #find all chatting friend list
    user_inst = request.user
    user_all_friends = ChatSession.objects.filter(Q(user1 = user_inst) | Q(user2 = user_inst)).select_related('user1','user2').order_by('-updated_on')
    all_friends = []

    for ch_session in user_all_friends:
        user,user_inst = [ch_session.user2,ch_session.user1] if request.user.username == ch_session.user1.username else [ch_session.user1,ch_session.user2]
        un_read_msg_count = ChatMessage.objects.filter(chat_session = ch_session.id,message_detail__read = False).exclude(user = user_inst).count()        
        data = {
            "user_name" : user.username,
            "room_name" : ch_session.room_group_name,
            "un_read_msg_count" : un_read_msg_count,
            "status" : user.profile_detail.is_online,
            "user_id" : user.id
        }
        all_friends.append(data)
    
    #find all suggested friend list
    user_1 = request.user
    user_all_friends = ChatSession.objects.filter(Q(user1 = user_1) | Q(user2 = user_1))
    user_list = []
    for ch_session in user_all_friends:
        user_list.append(ch_session.user1.id)
        user_list.append(ch_session.user2.id)
    all_user = User.objects.exclude(Q(username=user_1.username)|Q(id__in = list(set(user_list))))

    # extracting all message of given room name
    opposite_user = None
    fetch_all_message= None

    if room_name:
        current_user = request.user
        try:
            check_user = ChatSession.objects.filter(Q(id = room_name[5:])&(Q(user1 = current_user)|Q(user2 = current_user)))
        except Exception:
            return HttpResponse("Something went wrong!!!")
        if check_user.exists():
            chat_user_pair = check_user.first()
            opposite_user = chat_user_pair.user2 if chat_user_pair.user1.username == current_user.username else chat_user_pair.user1
            fetch_all_message = ChatMessage.objects.filter(chat_session__id = room_name[5:]).order_by('message_detail__timestamp')
        else:
            return HttpResponse("You have't permission to chatting with this user!!!")
    
    context = {'unread_msg':unread_msg,
               'user_list': all_friends,
               'all_user' : all_user,
               'room_name' : room_name,
                'opposite_user' : opposite_user,
                'fetch_all_message' : fetch_all_message}

    return render(request, 'chat/home.html', context)

@login_required
def create_friend(request,id):
    user_1 = request.user
    user_2 = get_object_or_404(User,id = id)
    get_create = ChatSession.create_if_not_exists(user_1,user_2)
    if get_create:
        room_name = get_create.room_group_name
        print(room_name)
        messages.add_message(request,messages.SUCCESS,f'{user_2.username} successfully added in your chat list!!')
        return redirect(f'/{room_name}')
    else:
        messages.add_message(request,messages.SUCCESS,f'{user_2.username} already added in your chat list!!')
    return redirect('/')
    

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="{%  static  'chat/css/style.css'  %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--FontAwesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <link rel='stylesheet prefetch'
    href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="nav-bar">
        <nav class="navbar navbar-expand-lg navbar-info bg-info">
            <div class="container">
                <a class="" href="{% url 'chat:home' %}">
                    <h1 style="margin:0; color:white">💬Chat App💬</h1>
                </a>
                {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white"> Hello {{request.user.username}} | </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'user:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'user:register' %}">Register <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'user:login' %}">Login</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </div>
    <hr style="margin:10px;" />
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <span hidden id='personal_room'>{{request.user.id}}</span>
    <script>

        const PersonalroomName = JSON.parse(document.getElementById('personal_room').textContent);
        let ws_scheme = window.location.protocol == "https:" ? "wss://" : "ws://";

        const PersonalSocket = new WebSocket(
            ws_scheme + window.location.host + '/ws/personal_chat/' + PersonalroomName + '/'
        );
        const set_online = () => {
            setTimeout(() => {
                PersonalSocket.send(JSON.stringify({
                    'msg_type': 'WENT_ONLINE',
                    'user_id': '{{request.user.id}}'
                }));
            }, 1000)
        }

        document.addEventListener("visibilitychange", event => {
            if (document.visibilityState == "visible") {
                if (PersonalSocket.readyState === WebSocket.OPEN) {
                    PersonalSocket.send(JSON.stringify({
                        'msg_type': 'WENT_ONLINE',
                        'user_id': '{{request.user.id}}'
                    }));
                }
            }
            else {
                if (PersonalSocket.readyState === WebSocket.OPEN) {
                    PersonalSocket.send(JSON.stringify({
                        'msg_type': 'WENT_OFFLINE',
                        'user_id': '{{request.user.id}}'
                    }));
                }
            }
        }
        );

        PersonalSocket.onmessage = (e) => {
            const data = JSON.parse(e.data);
            if (data.msg_type === 'WENT_ONLINE') {
                document.getElementById(data.user_name).querySelector('#status').style.color = 'rgb(11, 219, 73)';
            }

            else if (data.msg_type === 'WENT_OFFLINE') {
                document.getElementById(data.user_name).querySelector('#status').style.color = 'rgb(0, 0, 0)';
            }
        }

        PersonalSocket.onopen = set_online();
    </script>

    {% block script %}
    {% endblock %}

</body>

</html>